# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='broadcast date')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='time')),
                ('send_to_all', models.BooleanField(default=False, verbose_name='send to all')),
            ],
        ),
        migrations.CreateModel(
            name='ImageBroadcast',
            fields=[
                ('broadcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='broadcast.Broadcast')),
                ('image', models.ImageField(upload_to='')),
            ],
            bases=('broadcast.broadcast',),
        ),
        migrations.CreateModel(
            name='TextBroadcast',
            fields=[
                ('broadcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='broadcast.Broadcast')),
                ('message', models.TextField()),
            ],
            bases=('broadcast.broadcast',),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
