# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionBroadcast',
            fields=[
                ('broadcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='broadcast.Broadcast')),
                ('location', models.TextField(verbose_name='current Location')),
                ('destination', models.TextField(verbose_name='destination')),
                ('additional_info', models.TextField(verbose_name='additional information')),
            ],
            bases=('broadcast.broadcast',),
        ),
        migrations.CreateModel(
            name='RideBroadcast',
            fields=[
                ('broadcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='broadcast.Broadcast')),
                ('source', models.CharField(max_length=256, verbose_name='source')),
                ('dest', models.CharField(max_length=256, verbose_name='destination')),
                ('date_needed', models.DateField(default=django.utils.timezone.now, verbose_name='date needed')),
            ],
            bases=('broadcast.broadcast',),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='bc_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bcfrom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagebroadcast',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcaster', to=settings.AUTH_USER_MODEL),
        ),
    ]
