# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcast', '0002_auto_20160801_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='time')),
                ('broadcast_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_comment', to='broadcast.Broadcast')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='time')),
                ('broadcast_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_like', to='broadcast.Broadcast')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
