# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0006_auto_20160804_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='bc_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='rebc time'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='rebc date'),
        ),
    ]
