# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='University o ibadan', max_length=400, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='09020277797', max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]+$', 32), 'Only numbers are allowed.', 'invalid')], verbose_name='phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('driver', 'driver'), ('passenger', 'passenger')], default='admin', max_length=30, verbose_name='user type'),
            preserve_default=False,
        ),
    ]
