# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160709_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesharing',
            name='no_pass',
            field=models.IntegerField(max_length=256, verbose_name='no of passengers'),
        ),
    ]
