# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160709_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.CharField(max_length=256, verbose_name='pick up point')),
                ('dest', models.CharField(max_length=256, verbose_name='destination')),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registration date')),
                ('bearable', models.IntegerField(max_length=256, verbose_name='bearable cost')),
                ('status', models.CharField(default='pending', max_length=256, verbose_name='status')),
            ],
        ),
        migrations.AlterField(
            model_name='vehiclesharing',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], max_length=30, verbose_name='gender preference'),
        ),
        migrations.AddField(
            model_name='request',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.VehicleSharing'),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
