# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 01:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160710_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date sent')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='bearable',
            field=models.IntegerField(verbose_name='bearable cost'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(blank=True, verbose_name='no of seats'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(verbose_name='year of purchase'),
        ),
        migrations.AlterField(
            model_name='vehiclesharing',
            name='cost',
            field=models.IntegerField(verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='vehiclesharing',
            name='no_pass',
            field=models.IntegerField(verbose_name='no of passengers'),
        ),
    ]
