# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 02:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_message_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=250, verbose_name='information')),
                ('message', models.TextField(verbose_name='message')),
                ('date', models.DateField(default=datetime.datetime(2016, 7, 15, 2, 49, 35, 854038, tzinfo=utc), verbose_name='date')),
                ('read', models.BooleanField(default=False, verbose_name='read')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
