# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20160717_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesharing',
            name='ended',
            field=models.BooleanField(default=False, verbose_name='sharing ended'),
        ),
    ]
