# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_vehiclesharing_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='time sent'),
        ),
    ]
