# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 22:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20160720_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='followee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='followee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
