# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20160720_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesharing',
            name='details',
            field=models.TextField(default='Quick ride.', verbose_name='ride details'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(verbose_name='no of seats'),
        ),
    ]
