# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20160726_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(default='user.png', upload_to=''),
        ),
    ]
