# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20160808_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a verified user', verbose_name='user verified'),
        ),
    ]
