# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20160811_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(default='AdminCreated', max_length=10, verbose_name='liscenced plat number'),
        ),
    ]
