# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 21:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_vehicle_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liscence_no', models.CharField(max_length=30, verbose_name='liscence number')),
                ('date_issuance', models.DateField(verbose_name='date of first issuance')),
                ('scanned', models.ImageField(upload_to='', verbose_name="picture of driver's liscence")),
                ('confirmed', models.BooleanField(verbose_name='confirmed')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=10, verbose_name='liscenced plate number'),
        ),
    ]
