# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-28 21:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20160811_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(max_length=400, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='confirmed'),
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='date_issuance',
            field=models.DateField(blank=True, verbose_name='date of first issuance'),
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='scanned',
            field=models.ImageField(blank=True, upload_to='', verbose_name="picture of driver's liscence"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
